<<<<<<< HEAD
language: python
python:
  - "3.5.3"
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config
before_install:
  - mv travis_secrets.yaml secrets.yaml
=======
language: python
python:
  - "3.5.3"
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config
before_install:
  - mv travis_secrets.yaml secrets.yaml
>>>>>>> 1a322e1000bbfe71a6304b249192681cdcb2fe42
