homeassistant:
  name: Home
  latitude: -20.393
  longitude: -43.6419
  elevation: 1200
  unit_system: metric
  time_zone: America/Sao_Paulo
  customize: !include customize.yaml

notify:
  - name: html5
    platform: html5
    gcm_api_key: !secret html5_api_key
    gcm_sender_id: !secret html5_sender_id 


#introduction:

#frontend:

config:

http:
 api_password: !secret http_password
 ip_ban_enabled: True
 login_attempts_threshold: 50
 #ssl_certificate: /etc/letsencrypt/live/iot.charlessilva.com.br/fullchain.pem
 #ssl_key: /etc/letsencrypt/live/iot.charlessilva.com.br/privkey.pem
 #base_url: homeassistant.charlessilva.net.br


ifttt:
  key: !secret ifttt_key

sensor:
  - platform: travisci
    api_key: !secret travis_key
#    repository:
#     silvacharles/AndroidUtils
#     silvacharles/CSMobile
#     silvacharles/home-assistant-config
    monitored_conditions:
     state

mqtt:
  broker: 127.0.0.1
  port: 1883
  username: !secret user_mqtt
  password: !secret pass_mqtt
  keepalive: 60
  protocol: 3.1.1

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret
# track_new_calendar: true


recorder:
  purge_interval: 2
  purge_keep_days: 5
# db_url: sqlite:///home/homeassistant/.homeassistant/home-assistant.db
# db_url: !secret mysql_password
#  exclude:
#    domains:
#      - automation
#      - weblink
#      - updater
#    entities:
#      - sun.sun
#      - sensor.last_boot
#      - sensor.date

proximity:
  charles:
    devices:
    - device_tracker.charlessilva
    tolerance: 50
    unit_of_measurement: m

device_tracker:
  - platform: ddwrt
    host: 10.10.0.30
    username: !secret ddwrt_user
    password: !secret ddwrt_pass

  - platform: gpslogger

  - platform: bluetooth_tracker

#  - platform: ping
#    hosts:
#      roteador: 10.10.0.30

  - platform: icloud
    username: !secret icloud_user
    password: !secret icloud_pass
    account_name: CharlesIPad2

#  - platform: snmp
#    host: 100.64.13.169
#    community: public
#    baseoid: 1.3.6.1.2.1.4.22.1.2




updater:
  # include_used_components: true

discovery:

conversation:

history:

logbook:

sun:

map:

cloud:

scene:
  - name: Hora de dormir
    entities:
      switch.ac:
        state: off


panel_iframe:
  router:
    title: 'Site'
    icon: mdi:approval
    url: 'http://www.charlessilva.com.br'


sensor:
  - platform: yr

shopping_list:


tts:
  - platform: google
#    language: 'en'


group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
frontend: !include themes.yaml
