homeassistant:
  name: Home
  latitude: -21.2247
  longitude: -43.7667
  elevation: 1114
  unit_system: metric
  time_zone: America/Sao_Paulo
  customize: !include customize.yaml

#introduction:

frontend:

config:

http:
    api_password: !secret http_password
  # base_url: example.duckdns.org:8123

updater:
  # include_used_components: true

discovery:

conversation:

history:

logbook:

sun:

map:

cloud:

sensor:
  - platform: yr

tts:
  - platform: google

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
frontend: !include themes.yaml
