############################################################
#
# Logger
#
############################################################

# Log Severities: notset, debug, info, warn, warning, error, fatal, critical

#default: debug
default: info

logs:
  gsp: critical
  root: error
  openzwave: error
  libopenzwave: error
  py.warnings: error
  aiohttp.server: critical
  homeassistant.components.automation: debug
  homeassistant.components.script: debug
#  requests.packages.urllib3.connectionpool: warn
  requests.packages.urllib3.connectionpool: error
  homeassistant.setup: error
  homeassistant.core: critical
  homeassistant.exceptions: error
  homeassistant.helpers.script: error  
  homeassistant.helpers.entity: critical
  homeassistant.components.http: error
  homeassistant.components.zwave: error
  homeassistant.components.sensor: error
  homeassistant.components.recorder: error
  homeassistant.components.discovery: error
  homeassistant.components.automation: error
  homeassistant.components.climate.nest: error
  homeassistant.components.media_player: error
  homeassistant.components.device_tracker: error
  custom_components.media_player.sharptv: error
  homeassistant.components.emulated_hue: error
